name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install
      working-directory: ./frontend

    - name: Compilar
      run: npm run build
      working-directory: ./frontend

    - name: Executar testes
      run: npm run test
      working-directory: ./frontend
